import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class GuideSection {
  final int index;
  final IconData icon;
  final String title;
  final String subtitle;
  final String startsWith;
  final List<String> bulletPoints;

  GuideSection({
    required this.index,
    required this.icon,
    required this.title,
    required this.subtitle,
    required this.startsWith,
    required this.bulletPoints,
  });
}

class HelpGuideScreen extends StatefulWidget {
  const HelpGuideScreen({super.key});

  @override
  State<HelpGuideScreen> createState() => _HelpGuideScreenState();
}

class _HelpGuideScreenState extends State<HelpGuideScreen> {
  // Keeps track of currently expanded accordion sections. Getting Started (index 0) starts expanded S01
  final Set<int> _expandedSections = {0};

  final List<GuideSection> _sections = [
    GuideSection(
      index: 0,
      icon: Icons.play_arrow_outlined,
      title: 'Getting Started',
      subtitle: 'Set up your voice preferences, explore the main screen, and use demo mode if you want a guided sandbox first.',
      startsWith: 'Start by giving Buddy access to your camera and microphone so the assistant can begin describing your environment and answering your questions.',
      bulletPoints: [
        'Start by giving Buddy access to your camera and microphone so your assistant can begin describing your environment and answering your questions.',
        'Use the Home screen as your quick snapshot. It gives you instant access to core features like scene description, which is perfect for navigating your neighborhood or taking in the sights while traveling.',
        'Test out the text-to-speech feature by having Buddy read physical documents, like the specific address and shipping labels on your packages.',
        'Ask Buddy follow-up questions about what it sees in the frame. If you are coordinating your outfits, Buddy can confirm color matching and intricate clothing details instantly.',
      ],
    ),
    GuideSection(
      index: 1,
      icon: Icons.near_me_outlined,
      title: 'Everyday Navigation',
      subtitle: 'Learn how to use Buddy for getting around and identifying objects in real-time.',
      startsWith: 'Use the "Find Object" mode to locate specific items in a crowded space, like finding a misplaced notebook or locating your luggage at the airport.',
      bulletPoints: [
        'Use the "Find Object" mode to locate specific items in a crowded space, like finding a misplaced notebook or locating your luggage at the airport.',
        'Enable continuous description when walking. Buddy will narrate your surroundings in real-time, letting you know about obstacles, open doors, and signage as you move.',
        'Save frequent locations. Buddy can recognize familiar places and adjust its level of detail based on environments you already know well.',
      ],
    ),
    GuideSection(
      index: 2,
      icon: Icons.article_outlined,
      title: 'Reading and Documents',
      subtitle: 'Master the text-to-speech capabilities for letters, menus, and digital screens.',
      startsWith: 'Align your camera over a document until Buddy confirms all edges are visible, then hold still to capture and read a full page of text.',
      bulletPoints: [
        'Align your camera over a document until Buddy confirms all edges are visible, then hold still to capture and read a full page of text.',
        'Use the "Nearby Text" feature for quick reads. This is perfect for instantly reading cafe menus, checking prices, or translating street signs.',
        'Pinch to zoom in on smaller text, or let Buddy automatically enhance and read low-contrast text on computer screens and printed materials.',
      ],
    ),
    GuideSection(
      index: 3,
      icon: Icons.visibility_outlined,
      title: 'Buddy to EasyLens',
      subtitle: "Integrate your vision assistant with Snap Inc.'s AR lens creator to design and experience custom augmented reality.",
      startsWith: 'Link your accounts in the settings menu to allow Buddy to seamlessly communicate with the EasyLens platform.',
      bulletPoints: [
        'Link your accounts in the settings menu to allow Buddy to seamlessly communicate with the EasyLens platform.',
        'Use Buddy\'s voice recognition to dictate simple text prompts directly into EasyLens. This allows you to build custom AR filters and effects instantly using AI, without needing any technical design skills or manual typing.',
        'Have Buddy\'s advanced AI describe the Real-Time AR Previews generated by EasyLens. This helps you understand exactly how your interactive elements, virtual objects, or immersive augmented reality worlds look as they overlay your physical space.',
      ],
    ),
  ];

  void _toggleSection(int index) {
    setState(() {
      if (_expandedSections.contains(index)) {
        _expandedSections.remove(index);
      } else {
        _expandedSections.add(index);
      }
    });
  }

  Widget _buildStartHereCard() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.02),
            blurRadius: 16,
            offset: const Offset(0, 4),
          )
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Start Here',
                style: GoogleFonts.inter(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.black,
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                decoration: BoxDecoration(
                  color: const Color(0xFFEFF6FF),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(
                  '3 QUICK STEPS',
                  style: GoogleFonts.inter(
                    color: const Color(0xFF2563EB),
                    fontSize: 10,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 24),
          
          // Step 1
          _buildStartStepRow(
            icon: Icons.sentiment_satisfied_alt_outlined,
            title: '1. Meet Buddy',
            description: 'Set up your preferences first so your new vision assistant can tailor its audio descriptions, reading speed, and object recognition to your exact needs.',
          ),
          const SizedBox(height: 20),
          
          // Step 2
          _buildStartStepRow(
            icon: Icons.smartphone_outlined,
            title: '2. Scan your surroundings',
            description: 'Point your camera at anything to hear what\'s in front of you. Use it to quickly identify items around your room or have your books and documents read out loud.',
          ),
          const SizedBox(height: 20),
          
          // Step 3
          _buildStartStepRow(
            icon: Icons.menu_book_outlined,
            title: '3. Open only what you need',
            description: 'Tap any guide below to expand details instead of reading one long page all at once.',
          ),
        ],
      ),
    );
  }

  Widget _buildStartStepRow({
    required IconData icon,
    required String title,
    required String description,
  }) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          padding: const EdgeInsets.all(10),
          decoration: BoxDecoration(
            color: const Color(0xFFEFF6FF),
            borderRadius: BorderRadius.circular(12),
          ),
          child: Icon(icon, color: const Color(0xFF2563EB), size: 22),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style: GoogleFonts.inter(
                  fontWeight: FontWeight.bold,
                  fontSize: 15,
                  color: Colors.black,
                ),
              ),
              const SizedBox(height: 4),
              Text(
                description,
                style: GoogleFonts.inter(
                  fontSize: 12,
                  color: const Color(0xFF64748B),
                  height: 1.4,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildExpandableCard(GuideSection sec) {
    final isExpanded = _expandedSections.contains(sec.index);

    return Container(
      margin: const EdgeInsets.only(top: 16.0),
      width: double.infinity,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.02),
            blurRadius: 16,
            offset: const Offset(0, 4),
          )
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Card Header S01
          GestureDetector(
            onTap: () => _toggleSection(sec.index),
            behavior: HitTestBehavior.opaque,
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: const Color(0xFFEFF6FF),
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: Icon(sec.icon, color: const Color(0xFF2563EB), size: 24),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          sec.title,
                          style: GoogleFonts.inter(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                            color: Colors.black,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          sec.subtitle,
                          style: GoogleFonts.inter(
                            fontSize: 12,
                            color: const Color(0xFF64748B),
                            height: 1.3,
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(width: 12),
                  // Step count circle & indicator S01
                  Row(
                    children: [
                      Container(
                        width: 24,
                        height: 24,
                        decoration: const BoxDecoration(
                          color: Color(0xFFF1F5F9),
                          shape: BoxShape.circle,
                        ),
                        child: Center(
                          child: Text(
                            '${sec.bulletPoints.length}',
                            style: GoogleFonts.inter(
                              color: const Color(0xFF64748B),
                              fontSize: 11,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(width: 8),
                      Icon(
                        isExpanded ? Icons.keyboard_arrow_up : Icons.keyboard_arrow_down,
                        color: const Color(0xFF94A3B8),
                        size: 24,
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
          
          // Expanded Card Content S01
          if (isExpanded) ...[
            const Divider(height: 1, indent: 16, endIndent: 16),
            
            // "STARTS WITH" banner S01
            Container(
              margin: const EdgeInsets.all(16.0),
              padding: const EdgeInsets.all(16.0),
              decoration: BoxDecoration(
                color: const Color(0xFFF8FAFC),
                borderRadius: BorderRadius.circular(16),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'STARTS WITH',
                    style: GoogleFonts.inter(
                      color: const Color(0xFF2563EB),
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 0.5,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    sec.startsWith,
                    style: GoogleFonts.inter(
                      fontSize: 12,
                      color: const Color(0xFF64748B),
                      height: 1.4,
                    ),
                  ),
                ],
              ),
            ),
            
            // Bullet Points list S01
            Padding(
              padding: const EdgeInsets.fromLTRB(16.0, 0, 16.0, 24.0),
              child: Column(
                children: sec.bulletPoints.map((bp) {
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 12.0),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Padding(
                          padding: EdgeInsets.only(top: 6.0, right: 8.0),
                          child: Icon(Icons.brightness_1, size: 5, color: Color(0xFF94A3B8)),
                        ),
                        Expanded(
                          child: Text(
                            bp,
                            style: GoogleFonts.inter(
                              fontSize: 12,
                              color: const Color(0xFF64748B),
                              height: 1.4,
                            ),
                          ),
                        ),
                      ],
                    ),
                  );
                }).toList(),
              ),
            ),
          ],
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      body: SafeArea(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // 1. Floating Pill Back Button
              GestureDetector(
                onTap: () => Navigator.of(context).pop(),
                child: Container(
                  width: 95,
                  height: 44,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(22),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.06),
                        blurRadius: 8,
                        offset: const Offset(0, 3),
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      const Icon(Icons.chevron_left, color: Color(0xFF002663), size: 24),
                      const SizedBox(width: 4),
                      Text(
                        'Back',
                        style: GoogleFonts.inter(
                          color: const Color(0xFF002663),
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              
              const SizedBox(height: 32),
              
              // 2. Title Header
              Text(
                'Help Guide',
                style: GoogleFonts.inter(
                  fontSize: 32,
                  fontWeight: FontWeight.w900,
                  color: const Color(0xFF002663),
                ),
              ),
              
              const SizedBox(height: 24),
              
              // 3. Start Here Card
              _buildStartHereCard(),
              
              // 4. Expandable Accordion cards list S01
              ..._sections.map(_buildExpandableCard),
            ],
          ),
        ),
      ),
    );
  }
}
